---
title: "The emotional distress of being a new Twitter user"
subtitle: "All this social media stuff is hard."
summary: "All this social media stuff is hard."
slug: the-emotional-distress-of-being-a-new-twitter-user
authors:
 - admin
date: 2013-08-19
categories: ["Miscellaneous"]
tags: ["Facebook", "Google", "Linkedin", "Twitter", "Social networking"]
aliases: [/blog/2013/8/19/the-emotional-distress-of-being-a-new-twitter-user]
---
I’ve finally broken down. I’ve made a Twitter account. For years, I tried to hold off, thinking that Twitter was something for a younger generation, with a better stomach for cryptic text messages. The typical Twitter conversation is such a random stream of letters and special characters, made up of usernames, hashtags, and abbreviations of regular words, that it makes the winning entry of an obsfucated perl contest look outright legible. My thinking was that I gave up on perl for a reason. Why should I subject myself to Twitter? Anyway, this weekend I broke down and made a Twitter account. And I have to admit that it has its uses. While I don’t see myself doing long conversations over Twitter any time soon, I can see how it excels at disseminating and sharing information. 

However, now that I’m exploring Twitter, I’m experiencing an entirely novel form of emotional social-networking distress: Who do you follow? And, more importantly, if people you know in real life follow you on Twitter, do you have to follow them back? Nothing I’ve learned from my experience on other social networking sites has prepared me for this dilemma. LinkedIn is easy. I treat it as a professional address book. If I’ve met you in person or had a professional interaction with you, I’ll connect with you on LinkedIn. Facebook is the same but for purely social interactions. If I’ve met you in a social setting, I’ll connect with you on Facebook. Of all the services I know, Google+ is the closest to Twitter, since it doesn’t enforce reciprocal befriending. However, Google+ is easy too, because nobody uses it anyway, as far as I can tell. And in any case, Google+ always gives you the option to put people into the circle for “people I know but don’t really care about.”

So here are my Twitter rules, for now: If you’re a student in my lab, I’ll follow you, because I want to get to know you better. If you’re a family member, I’ll follow you, because it would be embarrassing not to. If I’m genuinely curious about you or your work, I’ll follow you. If I’m unsure if I should follow you or not, I’ll hold off for now. Since I’m still figuring all of this out, I’d rather have the list of people I’m following grow slowly than add a bunch of people right away and have to later remove them when I realize I wasn’t interested in them afterall.
