---
title: "A review of the therapeutic uses of very-low-carbohydrate (ketogenic) diets"
subtitle: "The European Journal of Clinical Nutrition just published a fantastic article summarizing the current knowledge about ketogenic diets."
summary: "The European Journal of Clinical Nutrition just published a fantastic article summarizing the current knowledge about ketogenic diets."
slug: a-review-of-the-therapeutic-uses-of-very-low-carbohydrate-ketogenic-diets
authors:
 - admin
date: 2013-09-01
categories: ["Nutrition"]
tags: ["Cancer", "Diabetes", "Heart disease", "Ketogenic diet", "Low-carb diet"]
aliases: [/blog/2013/9/1/a-review-of-the-therapeutic-uses-of-very-low-carbohydrate-ketogenic-diets]
---
I just learned about this review article that was published earlier this summer in the European Journal of Clinical Nutrition:

> A. Paoli, A. Rubini, J. S. Volek and K. A. Grimaldi. Beyond weight loss: a review of the therapeutic uses of very-low-carbohydrate (ketogenic) diets. *European Journal of Clinical Nutrition* **67**:789–796, 2013; [doi:10.1038/ejcn.2013.116](https://doi.org/10.1038/ejcn.2013.116)

This is a fantastic article summarizing the current knowledge about ketogenic diets. Read it!

**Update:** The article lists the following as diseases with strong evidence that ketogenic diets can be beneficial: obesity, cardiovascular disease, Type II diabetes, epilepsy. The article lists the following as diseases with emerging evidence that ketogenic diets can be beneficial: acne, cancer, polycystic ovary syndrome, neurological diseases (e.g. Alzheimer's).
 
