---
title: "Double Jeopardy"
subtitle: "Should reviewers re-review the same article for a different journal?"
summary: "Should reviewers re-review the same article for a different journal?"
slug: double-jeopardy
authors:
 - admin
date: 2014-09-13
categories: ["Academia"]
tags: ["Academic publishing", "Peer review", "Editing"]
aliases: [/blog/2014/9/13/double-jeopardy]
---

Lately it keeps happening to me that I try to invite somebody to review a paper and they decline, giving as reason that they have reviewed the paper already for a different journal[^1] and reviewing the paper again would put the authors into a situation of double jeopardy. This got me thinking. Should reviewers really decline for that reason? As reviewer, I've always thought the opposite. For a paper I have reviewed already, if the authors have made a reasonable effort to address my comments and have now chosen a more adequate journal, I can keep my review short and recommend acceptance. Thus, I'm actually preventing a situation of double jeopardy. I keep the authors from facing yet another reviewer with new opinions and requests. So, which is right? Should reviewers recuse themselves if they are asked to review again for a different journal, or should they instead leap at the opportunity and give the authors a break? I'd be interested in your thoughts.

[^1]: Where the paper was rejected, presumably.

