---
title: "Teaching a new introductory class in computational biology and bioinformatics"
subtitle: "Undergraduates will learn basic data wrangling, plotting, and programming with R and python."
summary: "Undergraduates will learn basic data wrangling, plotting, and programming with R and python."
slug: teaching-a-new-introductory-class-in-computational-biology-and-bioinformatics
authors:
 - admin
date:   2015-02-04
categories: ["Academia"]
tags: ["dplyr", "ggplot2", "python", "R", "Undergraduate education"]
aliases: [/blog/2015/2/4/teaching-a-new-introductory-class-in-computational-biology-and-bioinformatics]
---
This semester, I'm teaching a new introductory class in computational biology and bioinformatics. The class is primarily targeted at undergraduates, and it is split approximately 50:50 between R and python. The R component emphasizes effective data analysis and visualization, using packages such as ggplot2 and dplyr. The python component will introduce students to basic programming concepts, and it will also cover some typical bioinformatics applications.

Developing a new class is a lot of work, so I'll probably have much less time for posting here on my blog. However, on the flip side, the entire course content will be posted online, and you can [follow along here.](https://wilkelab.org/classes/SDS348_spring_2015.html) The core of each lecture is an in-class exercise worksheet, and I'm posting the worksheets and the solutions online. Many lectures also have a brief traditional lecture component with slides as well as additional reading materials. I'm developing the course as I go, so there will be new material posted twice a week throughout the spring.
